version: '3.8'

volumes:
  wireguard-config:

services:
  dashboard:
    build: .
    container_name: solidvpn
    ports:
      - "80:80"
    environment:
      - WG_CONFIG_DIR=/etc/wireguard
      - WG_INTERFACE=
      - WG_HOST=
      - WG_PORT=51820
      - WG_DEFAULT_NETWORK=
      - WG_ALLOWED_IPS=
    volumes:
      - wireguard-config:/etc/wireguard
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: solidvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - wireguard-config:/config
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
